spring:
  datasource:
    url: jdbc:h2:mem:testdb  # H2 ??? ?????? URL
    driver-class-name: org.h2.Driver  # H2 ?????? ????
    username: sa  # ?? ????
    password: 1234  # ?? ????
  h2:
    console:
      enabled: true  # H2 ?? ???
      path: /h2-console  # H2 ?? ?? (???: /h2-console)
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect  # JPA? ?? H2 Dialect ??
    hibernate:
      ddl-auto: update  # ??? ?? ??/????
    show-sql: true  # ???? SQL ?? ??
server:
  port: 8080  # ?????? ?? ??
